const placeholderCatalog = [
  { key: 'TEN_KHACH_HANG', group: 'Khách hàng', label: 'Tên khách hàng', source: 'Tên khách hàng trong hồ sơ' },
  { key: 'DIA_CHI_KHACH_HANG', group: 'Khách hàng', label: 'Địa chỉ khách hàng', source: 'Địa chỉ liên hệ trong hồ sơ' },
  { key: 'CCCD', group: 'Khách hàng', label: 'Số CCCD', source: 'CCCD của khách hàng cá nhân' },
  { key: 'DIEN_THOAI_KHACH_HANG', group: 'Khách hàng', label: 'Điện thoại khách hàng', source: 'Số điện thoại trong hồ sơ' },
  { key: 'MA_SO_THUE', group: 'Tổ chức', label: 'Mã số thuế', source: 'Mã số thuế của tổ chức' },
  { key: 'NGUOI_DAI_DIEN', group: 'Tổ chức', label: 'Người đại diện', source: 'Người đại diện của tổ chức' },
  { key: 'NGUOI_DAI_DIEN_KY', group: 'Tổ chức', label: 'Tên người ký', source: 'Người đại diện đã bỏ danh xưng Ông/Bà' },
  { key: 'CHUC_VU_NGUOI_DAI_DIEN', group: 'Tổ chức', label: 'Chức vụ người đại diện', source: 'Chức vụ trong thông tin tổ chức' },
  { key: 'CAN_CU_UY_QUYEN', group: 'Tổ chức', label: 'Căn cứ ủy quyền', source: 'Ghi chú ủy quyền trong hồ sơ' },
  { key: 'NGUOI_NHAN_BAN_GIAO', group: 'Tổ chức', label: 'Người nhận bàn giao', source: 'Liên hệ nhận bàn giao' },
  { key: 'CHUC_VU_NGUOI_NHAN_BAN_GIAO', group: 'Tổ chức', label: 'Chức vụ người nhận', source: 'Chức vụ người nhận bàn giao' },
  { key: 'SDT_NGUOI_NHAN_BAN_GIAO', group: 'Tổ chức', label: 'SĐT người nhận', source: 'Điện thoại người nhận bàn giao' },
  { key: 'TAI_SAN_THAM_DINH', group: 'Tài sản', label: 'Tài sản thẩm định', source: 'Mô tả tài sản trong hồ sơ' },
  { key: 'DIA_CHI_TAI_SAN', group: 'Tài sản', label: 'Địa chỉ tài sản', source: 'Địa chỉ thửa đất hoặc tài sản' },
  { key: 'MUC_DICH_THAM_DINH', group: 'Tài sản', label: 'Mục đích thẩm định', source: 'Mục đích trong hồ sơ' },
  { key: 'MUC_DICH_THAM_DINH_RUT_GON', group: 'Tài sản', label: 'Mục đích rút gọn', source: 'Mục đích đã rút gọn tự động' },
  { key: 'NGUON', group: 'Tài sản', label: 'Nguồn hồ sơ', source: 'Ngân hàng hoặc nguồn giới thiệu' },
  { key: 'SO_HOP_DONG', group: 'Hợp đồng', label: 'Số hợp đồng', source: 'Số hợp đồng đầy đủ trong hồ sơ' },
  { key: 'SO_HOP_DONG_VAN_BAN', group: 'Hợp đồng', label: 'Số hợp đồng văn bản', source: 'Số hợp đồng đã chuẩn hóa để đưa vào văn bản' },
  { key: 'NGAY_HOP_DONG', group: 'Hợp đồng', label: 'Ngày hợp đồng', source: 'Ngày hợp đồng dạng dd/mm/yyyy' },
  { key: 'NGAY_HOP_DONG_PLEIKU', group: 'Hợp đồng', label: 'Ngày hợp đồng kiểu Pleiku', source: 'Pleiku, ngày ... tháng ... năm ...' },
  { key: 'NGAY_HOP_DONG_NGAY', group: 'Hợp đồng', label: 'Ngày ký', source: 'Phần ngày của ngày hợp đồng' },
  { key: 'NGAY_HOP_DONG_THANG', group: 'Hợp đồng', label: 'Tháng ký', source: 'Phần tháng của ngày hợp đồng' },
  { key: 'NGAY_HOP_DONG_NAM', group: 'Hợp đồng', label: 'Năm ký', source: 'Phần năm của ngày hợp đồng' },
  { key: 'THANG_NAM_HOP_DONG', group: 'Hợp đồng', label: 'Tháng năm hợp đồng', source: 'Tháng ... năm ... của ngày hợp đồng' },
  { key: 'NGAY_CHUNG_THU', group: 'Chứng thư', label: 'Ngày chứng thư', source: 'Ngày chứng thư dạng dd/mm/yyyy' },
  { key: 'NGAY_CHUNG_THU_NGAY', group: 'Chứng thư', label: 'Ngày lập chứng thư', source: 'Phần ngày của ngày chứng thư' },
  { key: 'NGAY_CHUNG_THU_THANG', group: 'Chứng thư', label: 'Tháng lập chứng thư', source: 'Phần tháng của ngày chứng thư' },
  { key: 'NGAY_CHUNG_THU_NAM', group: 'Chứng thư', label: 'Năm lập chứng thư', source: 'Phần năm của ngày chứng thư' },
  { key: 'SO_BIEN_BAN_NGHIEM_THU', group: 'Văn bản', label: 'Số biên bản nghiệm thu', source: 'Số hợp đồng kèm hậu tố BBNT' },
  { key: 'SO_DE_NGHI_THANH_TOAN', group: 'Văn bản', label: 'Số đề nghị thanh toán', source: 'Sinh tự động từ số hợp đồng' },
  { key: 'PHI_THAM_DINH', group: 'Thanh toán', label: 'Phí thẩm định', source: 'Phí thẩm định đã định dạng tiền' },
  { key: 'PHI_THAM_DINH_BANG_CHU', group: 'Thanh toán', label: 'Phí bằng chữ', source: 'Phí thẩm định chuyển thành chữ' },
  { key: 'TAM_UNG', group: 'Thanh toán', label: 'Tiền tạm ứng', source: 'Số tiền tạm ứng đã định dạng' },
  { key: 'TAM_UNG_BANG_CHU', group: 'Thanh toán', label: 'Tạm ứng bằng chữ', source: 'Tiền tạm ứng chuyển thành chữ' },
  { key: 'CON_LAI_THANH_TOAN', group: 'Thanh toán', label: 'Còn lại thanh toán', source: 'Phí thẩm định trừ tiền tạm ứng' },
  { key: 'CON_LAI_THANH_TOAN_BANG_CHU', group: 'Thanh toán', label: 'Còn lại bằng chữ', source: 'Số tiền còn lại chuyển thành chữ' },
  { key: 'PHUONG_THUC_THANH_TOAN', group: 'Thanh toán', label: 'Phương thức thanh toán', source: 'Nội dung thanh toán theo cấu hình hợp đồng' },
  { key: 'NGAY', group: 'Ngày hiện tại', label: 'Ngày hiện tại', source: 'Ngày máy chủ lúc xuất văn bản' },
  { key: 'THANG', group: 'Ngày hiện tại', label: 'Tháng hiện tại', source: 'Tháng máy chủ lúc xuất văn bản' },
  { key: 'NAM', group: 'Ngày hiện tại', label: 'Năm hiện tại', source: 'Năm máy chủ lúc xuất văn bản' },
  { key: 'THANG_NAM', group: 'Ngày hiện tại', label: 'Tháng năm hiện tại', source: 'Tháng ... năm ... lúc xuất văn bản' },
  { key: 'NGAY_LAP_PLEIKU', group: 'Ngày hiện tại', label: 'Ngày lập kiểu Pleiku', source: 'Pleiku, ngày ... tháng ... năm ... lúc xuất' },
];

export default placeholderCatalog;
